### ISSUE TITLE
How to use? Is it the same as before? inav-Rangefinder-I2C-interface

### ISSUE THREAD

**Issue by lylus** [iNavFlight/inav-rangefinder#1]
How to use? Is it the same as before? inav-Rangefinder-I2C-interface？

**Comment by DzikuVx** [comment]
Yes, It is not yet in docs, but on the INAV side configuration is the same.

Here you need Arduino Pro Mini running 3.3V

**Comment by lylus** [comment]
@DzikuVx OK, thank you. I have a Arduino Pro Mini. Now I'll test it.
