### ISSUE TITLE
Max Range / Pulse timeout

### ISSUE THREAD

**Issue by mainframecn** [iNavFlight/inav-rangefinder#2]
Is de max range 300 correct? I seem to hit a limit of ~64 on i2c_regs[2]. Is that value cm? 
If i increase the value 300 and thus the pulse timeout it seems to get a lot closer to that 4 meters.
I'm no programmer or anything, just notice the "out of range" state triggers a lot faster than 4 meters, more like half a meter.

**Comment by DzikuVx** [comment]
There is not a chance for US-100 or HC-SR04 work up to 4m in flight. Even 3m is waaay to much. 1.5-2m is max for US-100 in perfect conditions

**Comment by mainframecn** [comment]
Just going of the code. It says 4meters:

#define MAX_RANGE 300 //Range of 4 meters
