### ISSUE TITLE
A4/A5 pin on schematic instead A5/A6

### ISSUE THREAD

**Issue by matthiasmicheldevelop** [iNavFlight/inav-rangefinder#3]
I have tu use A4/A5 pin for SDA/SCL Pins on the Arduino Mini Pro. Which are the correct I2c Pins.
 On the schematic there is A5/A6 connected.

**Comment by DzikuVx** [comment]
thanks, I've updated the diagram in cd5c57ca17403be167fae0fff412d40086bc2c8b
