### ISSUE TITLE
2.1.0-RC3 RANGEFINDER=UNAVAILABLE 

### ISSUE THREAD

**Issue by Robotto** [iNavFlight/inav-rangefinder#4]
Does not seem to work on.
# INAV/KAKUTEF4V2 2.1.0 Feb 10 2019 / 16:13:09 (0d3d0ff30)
Is there a specific firmware where this is confirmed working?

**Comment by Robotto** [comment]
ohsnap, i didn't compile the firmware with the right config.

for future reference, I added the following to /src/main/target/KAKUTEF4/target.h:
```
#define USE_RANGEFINDER
#define RANGEFINDER_I2C_BUS     BUS_I2C1
#define USE_RANGEFINDER_HCSR04_I2C
#define RANGEFINDER_HCSR04_I2C_I2C_INSTANCE (I2C_DEVICE)
```
and the following to /src/main/target/KAKUTEF4/target.mk:

```
drivers/rangefinder/rangefinder_hcsr04.c \
drivers/rangefinder/rangefinder_hcsr04_i2c.c \
```

**Comment by ThijnLans** [comment]
@Robotto where do you add that?

**Comment by Robotto** [comment]
> @Robotto where do you add that?

Here: https://github.com/iNavFlight/inav-rangefinder/issues/4#issuecomment-470858456

**Comment by ThijnLans** [comment]
I Kown but where do you at the 
/src/main/target/KAKUTEF4/target.h and the /src/main/target/KAKUTEF4/target.mk
?

**Comment by Robotto** [comment]
I'm sorry I don't understand the question.

Have you read the build guide? It's here:
https://github.com/iNavFlight/inav/wiki/Building-custom-firmware

**Comment by ThijnLans** [comment]
thanks for helping but I have a problem 
![image](https://user-images.githubusercontent.com/48473867/71902556-9d124e00-3162-11ea-9b9b-3f27eb427c83.png)
do you have an answer?

**Comment by Robotto** [comment]
Perhaps try 'make clean' before making?

**Comment by ThijnLans** [comment]
no that won't work

**Comment by Robotto** [comment]
Okay.
It seems that the linker is acting up. Try manually deleting build output
files, and make sure you're on a branch that supports the kakutef7mini
target.

**Comment by Robotto** [comment]
This discussion is turning into general troubleshooting.
May I suggest that you direct further questions to the inav group on
Telegram?

**Comment by thijn1234** [comment]
oke I flash the new firmware version but what now

**Comment by Robotto** [comment]
Now you fly.
