### ISSUE TITLE
Please add Kalman Filter Algorithm

### ISSUE THREAD

**Issue by whoim2** [iNavFlight/inav-rangefinder#9]
for HC-SR04 Ultrasonic

**Comment by digitalentity** [comment]
People seem to think that "Kalman Filter" or "EKF" are magic things that suddenly improve things a lot. INAV has it's own logic of dealing with unstable and unreliable sonar data, for that raw data with minimum possible delay suites the most.

**Comment by whoim2** [comment]
Sorry, del)
